version: "3.8"

services:
  app:
    image: eendlabs/eh-firestore
    build:
      context: ../
      dockerfile: ./build/package/app/Dockerfile
    depends_on:
      - firestore_emulator
    environment:
      FIRESTORE_EMULATOR_HOST: "firestore_emulator:8200"
      FIRESTORE_PROJECT_ID: "dummy-project-id"
    volumes:
      - ../:/eventhorizon
    working_dir: /eventhorizon

  firestore_emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:328.0.0-emulators
    environment:
      FIRESTORE_PROJECT_ID: "dummy-project-id"
    ports:
      - "8200:8200"
    entrypoint:
      - gcloud
      - beta
      - emulators
      - firestore
      - start
      - "--host-port=0.0.0.0:8200"